name: Run GRChombo Tests (Intel)

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    env:
      CHOMBO_HOME: ${{ github.workspace }}/Chombo/lib
      OMP_NUM_THREADS: 1

    steps:
    - name: Checkout Chombo
      uses: actions/checkout@v3
      with:
        repository: GRChombo/Chombo
        path: Chombo

    - name: Checkout GRChombo
      uses: actions/checkout@v3
      with:
        path: GRChombo

    - name: Install Chombo dependencies
      run: |
        # First update package repository mirrors
        sudo gem install apt-spy2
        sudo apt-spy2 check
        sudo apt-spy2 fix --commit
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install csh libgetopt-complete-perl

    - name: Install Intel compilers/MPI
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
        sudo apt-get -y install intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-compiler-fortran intel-oneapi-mkl intel-oneapi-mpi intel-oneapi-mpi-devel intel-oneapi-openmp
      working-directory: /tmp

    - name: Build Chombo
      run: |
        source /opt/intel/oneapi/setvars.sh
        cp $GITHUB_WORKSPACE/GRChombo/InstallNotes/MakeDefsLocalExamples/intel-no-hdf5-minimal.Make.defs.local $CHOMBO_HOME/mk/Make.defs.local
        make -j 4 AMRTimeDependent AMRTools BaseTools BoxTools
      working-directory: ${{ env.CHOMBO_HOME }}

    - name: Build GRChombo Tests
      run: |
        source /opt/intel/oneapi/setvars.sh
        make test -j 4
      working-directory: ${{ github.workspace }}/GRChombo

    - name: Run GRChombo Tests
      run: |
        source /opt/intel/oneapi/setvars.sh
        make run -j 2
      working-directory: ${{ github.workspace }}/GRChombo
