name: Run GRChombo Tests (GCC)

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    env:
      CHOMBO_HOME: ${{ github.workspace }}/Chombo/lib
      OMP_NUM_THREADS: 1

    steps:
    - name: Checkout Chombo
      uses: actions/checkout@v3
      with:
        repository: GRChombo/Chombo
        path: Chombo

    - name: Checkout GRChombo
      uses: actions/checkout@v3
      with:
        path: GRChombo

    - name: Install Chombo dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install csh gfortran-10 g++-10 cpp-10 libhdf5-dev libhdf5-openmpi-dev openmpi-bin libblas-dev liblapack-dev libgetopt-complete-perl

    - name: Set Compilers
      run: |
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
        sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 100
        sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-10 100

    - name: Build Chombo
      run: |
        cp $GITHUB_WORKSPACE/GRChombo/InstallNotes/MakeDefsLocalExamples/ubuntu-gcc.Make.defs.local $CHOMBO_HOME/mk/Make.defs.local
        make -j 4 AMRTimeDependent AMRTools BaseTools BoxTools
      working-directory: ${{ env.CHOMBO_HOME }}

    - name: Build GRChombo Tests
      run: make test -j 4
      working-directory: ${{ github.workspace }}/GRChombo

    - name: Run GRChombo Tests
      run: make run -j 2
      working-directory: ${{ github.workspace }}/GRChombo
